//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Data-Settings/PlayerInput Settings/No_Brains_Together/Player_1/Player_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Data-Settings/PlayerInput Settings/No_Brains_Together/Player_1/Player_Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Player_Actions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Player_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Player_Actions"",
    ""maps"": [
        {
            ""name"": ""Upper"",
            ""id"": ""22f42bc1-3339-4fc1-bafd-ba0007771ad7"",
            ""actions"": [
                {
                    ""name"": ""Move_LeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""acd645e8-13de-4fd6-af91-a5b2c8cb06f2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move_RightArm"",
                    ""type"": ""Button"",
                    ""id"": ""a541c716-de48-422d-a816-a93947b90125"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold_LeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""c3f1ac8e-d5d2-4860-8c02-feeb8bbec2ff"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold_RightArm"",
                    ""type"": ""Button"",
                    ""id"": ""8e0369e2-3f24-4da6-a180-607e3d7383c6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e8ce8a3b-8743-4293-a8ae-f7f1f558b80d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_LeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ed3c24-c08d-436f-90f6-e29883d8f7bb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_RightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abc07c79-546b-4856-84dd-85493428b120"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold_LeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07536ff0-c6af-409b-97d4-1f4cb5932644"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold_RightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Bottom"",
            ""id"": ""2cf7f79c-61bf-4c50-89f8-09f9e953e589"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""03e00d5b-9e15-4f1d-bd0b-af56dda5ad59"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""34f3f0cf-b5d1-480f-ae5a-025115a12fea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e951a417-b06a-4ae7-a52e-8f4b2f24956c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""34a78127-3b16-4f71-a911-cbe8eb5414f6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""507bfabd-27d5-4f5b-b809-0431178c1432"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8f033edd-d25b-4dbb-90eb-ccfbbf8fd28d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Upper
        m_Upper = asset.FindActionMap("Upper", throwIfNotFound: true);
        m_Upper_Move_LeftArm = m_Upper.FindAction("Move_LeftArm", throwIfNotFound: true);
        m_Upper_Move_RightArm = m_Upper.FindAction("Move_RightArm", throwIfNotFound: true);
        m_Upper_Hold_LeftArm = m_Upper.FindAction("Hold_LeftArm", throwIfNotFound: true);
        m_Upper_Hold_RightArm = m_Upper.FindAction("Hold_RightArm", throwIfNotFound: true);
        // Bottom
        m_Bottom = asset.FindActionMap("Bottom", throwIfNotFound: true);
        m_Bottom_Jump = m_Bottom.FindAction("Jump", throwIfNotFound: true);
        m_Bottom_Move = m_Bottom.FindAction("Move", throwIfNotFound: true);
    }

    ~@Player_Actions()
    {
        UnityEngine.Debug.Assert(!m_Upper.enabled, "This will cause a leak and performance issues, Player_Actions.Upper.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Bottom.enabled, "This will cause a leak and performance issues, Player_Actions.Bottom.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Upper
    private readonly InputActionMap m_Upper;
    private List<IUpperActions> m_UpperActionsCallbackInterfaces = new List<IUpperActions>();
    private readonly InputAction m_Upper_Move_LeftArm;
    private readonly InputAction m_Upper_Move_RightArm;
    private readonly InputAction m_Upper_Hold_LeftArm;
    private readonly InputAction m_Upper_Hold_RightArm;
    /// <summary>
    /// Provides access to input actions defined in input action map "Upper".
    /// </summary>
    public struct UpperActions
    {
        private @Player_Actions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UpperActions(@Player_Actions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Upper/Move_LeftArm".
        /// </summary>
        public InputAction @Move_LeftArm => m_Wrapper.m_Upper_Move_LeftArm;
        /// <summary>
        /// Provides access to the underlying input action "Upper/Move_RightArm".
        /// </summary>
        public InputAction @Move_RightArm => m_Wrapper.m_Upper_Move_RightArm;
        /// <summary>
        /// Provides access to the underlying input action "Upper/Hold_LeftArm".
        /// </summary>
        public InputAction @Hold_LeftArm => m_Wrapper.m_Upper_Hold_LeftArm;
        /// <summary>
        /// Provides access to the underlying input action "Upper/Hold_RightArm".
        /// </summary>
        public InputAction @Hold_RightArm => m_Wrapper.m_Upper_Hold_RightArm;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Upper; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UpperActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UpperActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UpperActions" />
        public void AddCallbacks(IUpperActions instance)
        {
            if (instance == null || m_Wrapper.m_UpperActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UpperActionsCallbackInterfaces.Add(instance);
            @Move_LeftArm.started += instance.OnMove_LeftArm;
            @Move_LeftArm.performed += instance.OnMove_LeftArm;
            @Move_LeftArm.canceled += instance.OnMove_LeftArm;
            @Move_RightArm.started += instance.OnMove_RightArm;
            @Move_RightArm.performed += instance.OnMove_RightArm;
            @Move_RightArm.canceled += instance.OnMove_RightArm;
            @Hold_LeftArm.started += instance.OnHold_LeftArm;
            @Hold_LeftArm.performed += instance.OnHold_LeftArm;
            @Hold_LeftArm.canceled += instance.OnHold_LeftArm;
            @Hold_RightArm.started += instance.OnHold_RightArm;
            @Hold_RightArm.performed += instance.OnHold_RightArm;
            @Hold_RightArm.canceled += instance.OnHold_RightArm;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UpperActions" />
        private void UnregisterCallbacks(IUpperActions instance)
        {
            @Move_LeftArm.started -= instance.OnMove_LeftArm;
            @Move_LeftArm.performed -= instance.OnMove_LeftArm;
            @Move_LeftArm.canceled -= instance.OnMove_LeftArm;
            @Move_RightArm.started -= instance.OnMove_RightArm;
            @Move_RightArm.performed -= instance.OnMove_RightArm;
            @Move_RightArm.canceled -= instance.OnMove_RightArm;
            @Hold_LeftArm.started -= instance.OnHold_LeftArm;
            @Hold_LeftArm.performed -= instance.OnHold_LeftArm;
            @Hold_LeftArm.canceled -= instance.OnHold_LeftArm;
            @Hold_RightArm.started -= instance.OnHold_RightArm;
            @Hold_RightArm.performed -= instance.OnHold_RightArm;
            @Hold_RightArm.canceled -= instance.OnHold_RightArm;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UpperActions.UnregisterCallbacks(IUpperActions)" />.
        /// </summary>
        /// <seealso cref="UpperActions.UnregisterCallbacks(IUpperActions)" />
        public void RemoveCallbacks(IUpperActions instance)
        {
            if (m_Wrapper.m_UpperActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UpperActions.AddCallbacks(IUpperActions)" />
        /// <seealso cref="UpperActions.RemoveCallbacks(IUpperActions)" />
        /// <seealso cref="UpperActions.UnregisterCallbacks(IUpperActions)" />
        public void SetCallbacks(IUpperActions instance)
        {
            foreach (var item in m_Wrapper.m_UpperActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UpperActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UpperActions" /> instance referencing this action map.
    /// </summary>
    public UpperActions @Upper => new UpperActions(this);

    // Bottom
    private readonly InputActionMap m_Bottom;
    private List<IBottomActions> m_BottomActionsCallbackInterfaces = new List<IBottomActions>();
    private readonly InputAction m_Bottom_Jump;
    private readonly InputAction m_Bottom_Move;
    /// <summary>
    /// Provides access to input actions defined in input action map "Bottom".
    /// </summary>
    public struct BottomActions
    {
        private @Player_Actions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public BottomActions(@Player_Actions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Bottom/Jump".
        /// </summary>
        public InputAction @Jump => m_Wrapper.m_Bottom_Jump;
        /// <summary>
        /// Provides access to the underlying input action "Bottom/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Bottom_Move;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Bottom; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="BottomActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(BottomActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="BottomActions" />
        public void AddCallbacks(IBottomActions instance)
        {
            if (instance == null || m_Wrapper.m_BottomActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BottomActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="BottomActions" />
        private void UnregisterCallbacks(IBottomActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="BottomActions.UnregisterCallbacks(IBottomActions)" />.
        /// </summary>
        /// <seealso cref="BottomActions.UnregisterCallbacks(IBottomActions)" />
        public void RemoveCallbacks(IBottomActions instance)
        {
            if (m_Wrapper.m_BottomActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="BottomActions.AddCallbacks(IBottomActions)" />
        /// <seealso cref="BottomActions.RemoveCallbacks(IBottomActions)" />
        /// <seealso cref="BottomActions.UnregisterCallbacks(IBottomActions)" />
        public void SetCallbacks(IBottomActions instance)
        {
            foreach (var item in m_Wrapper.m_BottomActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BottomActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="BottomActions" /> instance referencing this action map.
    /// </summary>
    public BottomActions @Bottom => new BottomActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Upper" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UpperActions.AddCallbacks(IUpperActions)" />
    /// <seealso cref="UpperActions.RemoveCallbacks(IUpperActions)" />
    public interface IUpperActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move_LeftArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_LeftArm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Move_RightArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_RightArm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hold_LeftArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHold_LeftArm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hold_RightArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHold_RightArm(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Bottom" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="BottomActions.AddCallbacks(IBottomActions)" />
    /// <seealso cref="BottomActions.RemoveCallbacks(IBottomActions)" />
    public interface IBottomActions
    {
        /// <summary>
        /// Method invoked when associated input action "Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
    }
}
