//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Data-Settings/PlayerInput Settings/No_Brains_Together/Player_1/Player_1_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Data-Settings/PlayerInput Settings/No_Brains_Together/Player_1/Player_1_Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Player_1_Actions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Player_1_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Player_1_Actions"",
    ""maps"": [
        {
            ""name"": ""Upper"",
            ""id"": ""22f42bc1-3339-4fc1-bafd-ba0007771ad7"",
            ""actions"": [
                {
                    ""name"": ""Move_LeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""acd645e8-13de-4fd6-af91-a5b2c8cb06f2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move_RightArm"",
                    ""type"": ""Button"",
                    ""id"": ""a541c716-de48-422d-a816-a93947b90125"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold_LeftArm"",
                    ""type"": ""Button"",
                    ""id"": ""c3f1ac8e-d5d2-4860-8c02-feeb8bbec2ff"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold_RightArm"",
                    ""type"": ""Button"",
                    ""id"": ""8e0369e2-3f24-4da6-a180-607e3d7383c6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e8ce8a3b-8743-4293-a8ae-f7f1f558b80d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_LeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ed3c24-c08d-436f-90f6-e29883d8f7bb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move_RightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abc07c79-546b-4856-84dd-85493428b120"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold_LeftArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07536ff0-c6af-409b-97d4-1f4cb5932644"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold_RightArm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Upper
        m_Upper = asset.FindActionMap("Upper", throwIfNotFound: true);
        m_Upper_Move_LeftArm = m_Upper.FindAction("Move_LeftArm", throwIfNotFound: true);
        m_Upper_Move_RightArm = m_Upper.FindAction("Move_RightArm", throwIfNotFound: true);
        m_Upper_Hold_LeftArm = m_Upper.FindAction("Hold_LeftArm", throwIfNotFound: true);
        m_Upper_Hold_RightArm = m_Upper.FindAction("Hold_RightArm", throwIfNotFound: true);
    }

    ~@Player_1_Actions()
    {
        UnityEngine.Debug.Assert(!m_Upper.enabled, "This will cause a leak and performance issues, Player_1_Actions.Upper.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Upper
    private readonly InputActionMap m_Upper;
    private List<IUpperActions> m_UpperActionsCallbackInterfaces = new List<IUpperActions>();
    private readonly InputAction m_Upper_Move_LeftArm;
    private readonly InputAction m_Upper_Move_RightArm;
    private readonly InputAction m_Upper_Hold_LeftArm;
    private readonly InputAction m_Upper_Hold_RightArm;
    /// <summary>
    /// Provides access to input actions defined in input action map "Upper".
    /// </summary>
    public struct UpperActions
    {
        private @Player_1_Actions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public UpperActions(@Player_1_Actions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Upper/Move_LeftArm".
        /// </summary>
        public InputAction @Move_LeftArm => m_Wrapper.m_Upper_Move_LeftArm;
        /// <summary>
        /// Provides access to the underlying input action "Upper/Move_RightArm".
        /// </summary>
        public InputAction @Move_RightArm => m_Wrapper.m_Upper_Move_RightArm;
        /// <summary>
        /// Provides access to the underlying input action "Upper/Hold_LeftArm".
        /// </summary>
        public InputAction @Hold_LeftArm => m_Wrapper.m_Upper_Hold_LeftArm;
        /// <summary>
        /// Provides access to the underlying input action "Upper/Hold_RightArm".
        /// </summary>
        public InputAction @Hold_RightArm => m_Wrapper.m_Upper_Hold_RightArm;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Upper; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="UpperActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(UpperActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="UpperActions" />
        public void AddCallbacks(IUpperActions instance)
        {
            if (instance == null || m_Wrapper.m_UpperActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UpperActionsCallbackInterfaces.Add(instance);
            @Move_LeftArm.started += instance.OnMove_LeftArm;
            @Move_LeftArm.performed += instance.OnMove_LeftArm;
            @Move_LeftArm.canceled += instance.OnMove_LeftArm;
            @Move_RightArm.started += instance.OnMove_RightArm;
            @Move_RightArm.performed += instance.OnMove_RightArm;
            @Move_RightArm.canceled += instance.OnMove_RightArm;
            @Hold_LeftArm.started += instance.OnHold_LeftArm;
            @Hold_LeftArm.performed += instance.OnHold_LeftArm;
            @Hold_LeftArm.canceled += instance.OnHold_LeftArm;
            @Hold_RightArm.started += instance.OnHold_RightArm;
            @Hold_RightArm.performed += instance.OnHold_RightArm;
            @Hold_RightArm.canceled += instance.OnHold_RightArm;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="UpperActions" />
        private void UnregisterCallbacks(IUpperActions instance)
        {
            @Move_LeftArm.started -= instance.OnMove_LeftArm;
            @Move_LeftArm.performed -= instance.OnMove_LeftArm;
            @Move_LeftArm.canceled -= instance.OnMove_LeftArm;
            @Move_RightArm.started -= instance.OnMove_RightArm;
            @Move_RightArm.performed -= instance.OnMove_RightArm;
            @Move_RightArm.canceled -= instance.OnMove_RightArm;
            @Hold_LeftArm.started -= instance.OnHold_LeftArm;
            @Hold_LeftArm.performed -= instance.OnHold_LeftArm;
            @Hold_LeftArm.canceled -= instance.OnHold_LeftArm;
            @Hold_RightArm.started -= instance.OnHold_RightArm;
            @Hold_RightArm.performed -= instance.OnHold_RightArm;
            @Hold_RightArm.canceled -= instance.OnHold_RightArm;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="UpperActions.UnregisterCallbacks(IUpperActions)" />.
        /// </summary>
        /// <seealso cref="UpperActions.UnregisterCallbacks(IUpperActions)" />
        public void RemoveCallbacks(IUpperActions instance)
        {
            if (m_Wrapper.m_UpperActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="UpperActions.AddCallbacks(IUpperActions)" />
        /// <seealso cref="UpperActions.RemoveCallbacks(IUpperActions)" />
        /// <seealso cref="UpperActions.UnregisterCallbacks(IUpperActions)" />
        public void SetCallbacks(IUpperActions instance)
        {
            foreach (var item in m_Wrapper.m_UpperActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UpperActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="UpperActions" /> instance referencing this action map.
    /// </summary>
    public UpperActions @Upper => new UpperActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Upper" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="UpperActions.AddCallbacks(IUpperActions)" />
    /// <seealso cref="UpperActions.RemoveCallbacks(IUpperActions)" />
    public interface IUpperActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move_LeftArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_LeftArm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Move_RightArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove_RightArm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hold_LeftArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHold_LeftArm(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Hold_RightArm" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHold_RightArm(InputAction.CallbackContext context);
    }
}
